name: CI pull request

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  image-name: ghcr.io/henrymrrtt67/samples.weatherforecast:${{ github.sha }}
  image-name-unit-tests: unit-tests:latest

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Unit tests [build]
        run: docker build --target unit-test -t ${{ env.image-name-unit-tests }} .
      
      - name: Unit tests [run]
        run: docker run --rm -v ${{ github.workspace }}/out/test/testresults:/code/test/Samples.WeatherForecast.Api.UnitTest/TestResults ${{ env.image-name-unit-tests }}

      - name: Code Coverage [Code Climate]
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 
        with:
          files: ${{ github.workspace }}/out/test/testresults/coverage.info
          prefix: /code/
      
      - name: App [build]
        run: docker build . -t ${{ env.image-name }}

      - name: App [scan]
        uses: azure/container-scan@v0
        with:
          image-name: ${{ env.image-name }}
          severity-threshold: MEDIUM
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_CR }}